name: Build and Push Go Image to Google Cloud Platform

on:
  push:
    branches:
    - 'GCP'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
      run: |
        gcloud auth configure-docker ${{ secrets.REGISTRY_URL }} --quiet
        docker build -t${{ secrets.REGISTRY_URL }}/$GOOGLE_PROJECT/images/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.REGISTRY_URL }}/$GOOGLE_PROJECT/images/${{ secrets.IMAGE_NAME }}:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.PROJECT_ID }}
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deploy.yaml
        kubectl apply -f deply.yaml
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ingress.yaml
        kubectl apply -f ingress.yaml
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" services.yaml
        kubectl apply -f services.yaml